[versions]
agp = "8.5.1"
playServicesWearable = "19.0.0"
wear = "1.3.0"
retrofit = "2.9.0"
lifecycle = "2.8.0"
library = "3.2.0-alpha11"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
wear = { group = "androidx.wear", name = "wear", version.ref = "wear" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
#library = { group = "androidx.databinding", name = "library", version.ref = "library" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

